### PR TITLE
Add parameter order-index

### LINKED ISSUE #312: Support order index for parameters
## Problem

Parameter order right now is determined by the parameter ID. This is bad because reordering parameters requires changing the ID, which basically means removing the parameter and adding a new one. This renders template upgrades really difficult.

## Solution

Introduce a new attribute for each parameter that indicates the position in the ordering. It should be an integer and the parameters will be sorted by this index and then by ID if there is a tie. If a parameter does not have an index it will be shown in the end.

### Example

```
parameters = {
  "username" = {
    name = "Username"
    type = string
    order-index = 1
  }
  "password" = {
    name = "Password"
    secret = true
    order-index = 2
  }
  "http-port" = {
    name = "HTTP Port"
    default = 80
    order-index = 3
  }
}
```

### PR DESCRIPTION
**Pull request by FRosner**
fixes #312

### CODE REVIEW

**Comment by FRosner** [comment]
I am going to reduce code duplication a bit

**Comment by FRosner** [comment]
Much better. Feel free to review now @Gerrrr  ))

**Comment by Gerrrr** [comment]
Sure, I am going to take a look during this weekend.

**Review by Gerrrr — APPROVED** [review]
LGTM!

**Pull request closed without merging**
