### PR TITLE
Services for creating, retrieving , updating and deleting instances 

### PR DESCRIPTION
**Pull request by IshmeetKaur**
- Services for CRUD operations in broccoliService.js.
- Seperated the CSS code from index.html to index.css and images in the images folder.

### CODE REVIEW

**Comment by FRosner** [comment]
Can we go through in person when you have some basic tests @IshmeetKaur?

**Comment by FRosner** [comment]
@IshmeetKaur you are trying to merge tons of commit I did. Where did you get them from? 😈

**Comment by IshmeetKaur** [comment]
Actually , I tried to commit my work and then pulled the changes from the forked repository because of which all your commits are also shown.

**Comment by FRosner** [comment]
Something went wrong :D Let's look at it together on Monday?

**Comment by IshmeetKaur** [comment]
Okk..Sure
Thanks :)

**Comment by IshmeetKaur** [comment]
Okk..Sure
Thanks :)

**Pull request closed without merging**
