### PR TITLE
GH-44: Add HTTP API endpoint to get instance tasks

### PR DESCRIPTION
**Pull request by swsnr**

### CODE REVIEW

**Comment by FRosner** [comment]
We need to document this endpoint in the Wiki. Can you provide some documentation similar to the one available already: https://github.com/FRosner/cluster-broccoli/wiki/HTTP-API-v1?

**Comment by swsnr** [comment]
@FRosner Shouldn't I do that *after* merging?  Why do we not move the documentation into the repository itself (which is where it belongs in my opinion)?

**Comment by FRosner** [comment]
Agreed we should move it. I wanted to have it here before merging so I can review it. But if it is part of the code that would be even better. Do you need any support?

**Comment by swsnr** [comment]
I'll add docs.

**Comment by swsnr** [comment]
@FRosner Added docs: https://github.com/FRosner/cluster-broccoli/wiki/HTTP-API-v1#apiv1instancesinstanceidtasks

**Comment by FRosner** [comment]
The curl command in the docs seems wrong? `curl -X GET 'localhost:9000/api/v1/instances/`. I'm going to update it.

**Comment by swsnr** [comment]
@FRosner Wrong? In how far?  Please be specific.

**Comment by FRosner** [comment]
First of all it is missing a quote.

image

After adding it, I'm getting an error that the route cannot be found. Which is because it is wrong, no? It should be `curl -X GET 'localhost:9000/api/v1/instances/my-http/tasks'`

**Review by FRosner — COMMENTED** [review]
LGTM

**Review by FRosner — APPROVED** [review]

**Comment by swsnr** [comment]
@FRosner Ah, my bad.  Sorry, and thanks for fixing.

**Pull request merged**
