### PR TITLE
Adjust templates path config property

### PR DESCRIPTION
**Pull request by FRosner**

### CODE REVIEW

**Review by Gerrrr — APPROVED** [review]

**Comment by swsnr** [comment]
I'm documenting `reference.conf` in #284 and all this from `README.md`, as it's already documented in `reference.conf`.

**Comment by FRosner** [comment]
So we should close this one?

**Comment by FRosner** [comment]
@lunaryorn ping :)

**Comment by swsnr** [comment]
@FRosner I would say yes… I thought we agreed on documenting all settings in `reference.conf`, didn't we?

**Comment by FRosner** [comment]
Yes I just wanted to confirm that I remembered it correctly.

**Pull request closed without merging**
