### PR TITLE
Show actual resource usage of tasks

### PR DESCRIPTION
**Pull request by swsnr**
Addresses #287 

# TODO

- [x] Get required resources from Job description
- [x] Implement TODO tests
- [x] Show fancy graphs for resource allocation in frontend
- [x] Show numbers in tooltips on hover

### CODE REVIEW

**Comment by swsnr** [comment]
@FRosner Finished.  Can you review?

**Comment by swsnr** [comment]
That's how it looks currently:




Progress bars are red for >= 100% consumption, orange (warning) for >= 80% consumption, and green for <80% consumption.

**Comment by swsnr** [comment]
@FRosner Ping :)

**Comment by FRosner** [comment]
omw!

**Comment by FRosner** [comment]
LGTM. However I think we should have the percentage fixed and in the middle of the progress bar. There are two reasons for that:

1. The value is 0% but it visually shows like 20%.
2. The value exceeds 100% and the number disappears from the screen.

broccolicpu

**Review by FRosner — DISMISSED** [review]
the gif is broken. I am trying to create a new one.

**Comment by swsnr** [comment]
@FRosner Can you review again?

**Comment by FRosner** [comment]
yup

**Review by FRosner — APPROVED** [review]
LGTM thank you!

**Pull request merged**
