### PR TITLE
WIP: Move settings to application.conf

### PR DESCRIPTION
**Pull request by swsnr**
We don't really need a reference.conf imho since we don't have
multiple configurations in our application.

### CODE REVIEW

**Comment by swsnr** [comment]
@FRosner Ready now, can you review and merge once tests pass?

**Comment by FRosner** [comment]
Accidental close?

**Comment by swsnr** [comment]
No, I think we should keep reference.conf for documentation purposes, and I'm preparing a PR to add comments to it.

**Comment by FRosner** [comment]
Awesome! I think this is a great idea.

**Comment by swsnr** [comment]
@FRosner  👉 #284

**Pull request closed without merging**
