### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by swsnr**
Clean compile before:

```
[info] Compiling 84 Scala sources and 2 Java sources to /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/target/scala-2.11/classes...
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/services/InstanceService.scala:54: implicit numeric widening
[warn]   private val scheduledTask = scheduler.scheduleAtFixedRate(task, 0, pollingFrequencySeconds, TimeUnit.SECONDS)
[warn]                                                                      ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/Global.scala:6: trait GlobalSettings in package api is deprecated: Use dependency injection
[warn] object Global extends GlobalSettings {
[warn]                       ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/controllers/AuthConfigImpl.scala:64: method maybeApplication in object Play is deprecated: This is a static reference to application, use DI instead
[warn]     cookieSecureOption = play.api.Play.maybeApplication.exists(app => play.api.Play.isProd(app) && cookieSecure),
[warn]                                        ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/controllers/AuthConfigImpl.scala:64: method isProd in object Play is deprecated: inject the play.api.Environment instead
[warn]     cookieSecureOption = play.api.Play.maybeApplication.exists(app => play.api.Play.isProd(app) && cookieSecure),
[warn]                                                                                     ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/controllers/WebSocketController.scala:66: method tryAccept in object WebSocket is deprecated: Use acceptOrResult with an Akka streams flow instead
[warn]   def socket: WebSocket = WebSocket.tryAccept[Msg](requestToSocket)
[warn]                                     ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/services/FileSystemInstanceStorage.scala:51: non-nullary method overrides nullary method
[warn]   protected override def readInstancesImpl(): Try[Set[Instance]] =
[warn]                          ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:35: method remove in object Cache is deprecated: Inject CacheApi into your component
[warn]     Cache.remove(token + tokenSuffix)
[warn]           ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:35: method current in object Play is deprecated: This is a static reference to application, use DI instead
[warn]     Cache.remove(token + tokenSuffix)
[warn]                 ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:39: method get in object Cache is deprecated: Inject CacheApi into your component
[warn]     Cache.get(token + tokenSuffix).map(_.asInstanceOf[Id])
[warn]           ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:39: method current in object Play is deprecated: This is a static reference to application, use DI instead
[warn]     Cache.get(token + tokenSuffix).map(_.asInstanceOf[Id])
[warn]              ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:42: method set in object Cache is deprecated: Inject CacheApi into your component
[warn]     Cache.set(token + tokenSuffix, userId, timeoutInSeconds)
[warn]           ^
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/jp/t2v/lab/play2/auth/MultiLoginCacheIdContainer.scala:42: method current in object Play is deprecated: This is a static reference to application, use DI instead
[warn]     Cache.set(token + tokenSuffix, userId, timeoutInSeconds)
[warn]              ^
[warn] 12 warnings found
[success] Total time: 43 s, completed 16.08.2017 12:47:43
```

And after:

```
[info] Compiling 85 Scala sources and 2 Java sources to /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/target/scala-2.11/classes...
[warn] /Users/swiesner/GitHub/FRosner/cluster-broccoli/server/src/main/scala/de/frosner/broccoli/controllers/WebSocketController.scala:70: method tryAccept in object WebSocket is deprecated: Use acceptOrResult with an Akka streams flow instead
[warn]   def socket: WebSocket = WebSocket.tryAccept[Msg](requestToSocket)
[warn]                                     ^
[warn] one warning found
```

### CODE REVIEW

**Review by FRosner — DISMISSED** [review]
LGTM

**Comment by swsnr** [comment]
@FRosner Can you please review again?

**Review by FRosner — DISMISSED** [review]
LGTM. What did you change from the last review?

**Comment by swsnr** [comment]
@FRosner I rebased and solve some merge conflicts; for the same reason you'll need to review again after my next push :)

**Comment by swsnr** [comment]
@FRosner That is, now :)

**Review by FRosner — APPROVED** [review]

**Pull request merged**
